SPREADSHEET_TO_USE_NAME = '/var/linux-admin-toolkit/server_inventory_import_export.xls'

PROJECT_TABLE_PREFIX= 'admin_gui_'

MODEL_TO_SPREADSHEET_MAP = {
    'enclosure' : [
        ['self','enclosure_name', 1],
        ['self','primary_ip_address',2],
        ['self','point_of_contact',3],
        ['self','status',4],
        ['self','location_code', 5],                    
        ['self','note', 8],
        ['default','ip_active','False'],
    ],
    'enclosure_detail' : [        
        ['link',['enclosure','enclosure_name','enclosure_id'], 1],
        ['self','service_tag',6],
        ['self','model', 7 ]          
    ],
    'enclosure_additional_ip' : [               
        ['link',['enclosure','enclosure_name','enclosure_id'], 1],
        ['self','additional_ip',2],
        ['default','ip_active','False'],
    ],
    'enclosure_wire_run' : [        
        ['link',['enclosure','enclosure_name','enclosure_id'], 1],
        ['self','source_port',2],
        ['self','destination_name',3],
        ['self','destination_port',4],            
    ],
    'physical' : [
        ['self','physical_name',1],
        ['self','primary_ip_address',2],
        ['self','role',3],
        ['self','purpose',4],
        ['self','point_of_contact',5],
        ['link',['enclosure','enclosure_name','host_enclosure_name_id'], 6],
        ['self','status',7],
        ['self','note',17],   
        ['default','ip_active','False'],
        ['default','selected','False'],     
    ],       
    'physical_detail' : [
        ['link',['physical','physical_name','physical_id'], 1],
        ['self','location_code',8],
        ['self','service_tag',9],
        ['self','console_address',10],
        ['self','os',11],
        ['self','model',12],
        ['self','size',13],   
        ['default','console_ip_active','False'],              
    ],
    'physical_services' : [        
        ['link',['physical','physical_name','physical_id'], 1],
        ['self','admin_cluster_group_01',14],
        ['self','admin_cluster_group_02',15],
        ['self','script_profile',16],
    ],
    'physical_additional_ip' : [        
        ['link',['physical','physical_name','physical_id'], 1],
        ['self','additional_ip',2], 
        ['default','ip_active','False'],           
    ],    
    'physical_wire_run' : [        
        ['link',['physical','physical_name','physical_id'], 1],
        ['self','source_port',2],
        ['self','destination_name',3],
        ['self','destination_port',4],                        
    ],
    'linux_virtual' : [
        ['self','linux_virtual_name', 1],
        ['self','primary_ip_address',2],
        ['self','role',3],
        ['self','purpose',4],
        ['self','point_of_contact', 5],                            
        ['link',['physical','physical_name','host_physical_name_id'], 6],
        ['self','status', 7],
        ['self','note', 14],  
        ['default','ip_active','False'],  
        ['default','selected','False'],        
    ],
    'linux_virtual_detail' : [
        ['link',['linux_virtual','linux_virtual_name','linux_virtual_id'], 1],
        ['self','size',8],
        ['self','os',9],
        ['self','base_image',10],           
    ],
    'linux_virtual_services' : [
        ['link',['linux_virtual','linux_virtual_name','linux_virtual_id'], 1],
        ['self','admin_cluster_group_01',11],
        ['self','admin_cluster_group_02',12],
        ['self','script_profile',13],                   
    ],
    'linux_virtual_additional_ip' : [        
        ['link',['linux_virtual','linux_virtual_name','linux_virtual_id'], 1],
        ['self','additional_ip',2],    
        ['default','ip_active','False'],        
    ], 
    'other_virtual' : [
        ['self','other_virtual_name', 1],
        ['self','primary_ip_address',2],
        ['self','role',3],
        ['self','purpose',4],
        ['self','point_of_contact', 5],                            
        ['link',['physical','physical_name','host_physical_name_id'], 6],
        ['self','status', 7],
        ['self','note', 11],  
        ['default','ip_active','False'],                  
    ],
    'other_virtual_detail' : [
        ['link',['other_virtual','other_virtual_name','other_virtual_id'], 1],
        ['self','size',8],
        ['self','os',9],
        ['self','base_image',10],           
    ],    
    'other_virtual_additional_ip' : [        
        ['link',['other_virtual','other_virtual_name','other_virtual_id'], 1],
        ['self','additional_ip',2],    
        ['default','ip_active','False'],        
    ], 
    'storage' : [
        ['self','storage_name',1],
        ['self','primary_ip_address',2],
        ['self','purpose',3],
        ['self','point_of_contact',4],
        ['self','status',5],
        ['self','location_code',6],
        ['self','service_tag',7],
        ['self','model',8],
        ['self','note',9], 
        ['default','ip_active','False'],
    ],       
    'storage_additional_ip' : [
        ['link',['storage','storage_name','storage_id'], 1],
        ['self','additional_ip',2], 
        ['default','ip_active','False'],         
    ],
    'storage_wire_run' : [
        ['link',['storage','storage_name','storage_id'], 1],
        ['self','source_port',2],
        ['self','destination_name',3],
        ['self','destination_port',4],                        
    ],  
    'storage_volume' : [
        ['self','volume_name',1],
        ['self','size',2],
        ['self','mount_point',3],
        ['self','role',4],
        ['self','purpose',5],
        ['link',['storage','storage_name','host_storage_name_id'], 6],
        ['self','status',7],        
    ],       
    'storage_volume_note' : [
        ['link',['storage_volume','volume_name','storage_volume_id'], 1],
        ['self','note',2],          
    ],
    'network' : [
        ['self','network_name',1],
        ['self','primary_ip_address',2],
        ['self','purpose',3],
        ['self','point_of_contact',4],
        ['self','status',5],
        ['self','location_code',6],
        ['self','service_tag',7],
        ['self','model',8],
        ['self','note',9], 
        ['default','ip_active','False'],
    ],       
    'network_additional_ip' : [
        ['link',['network','network_name','network_id'], 1],
        ['self','additional_ip',2], 
        ['default','ip_active','False'],         
    ], 
    'network_wire_run' : [
        ['link',['network','network_name','network_id'], 1],
        ['self','source_port',2],
        ['self','destination_name',3],
        ['self','destination_port',4],                        
    ],                               
}
